# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/model/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\Users\\Ir√®ne\\Documents\\heavy-metal-notifier-rs\\src\\model\\store\\migrations"
